### PR TITLE
Fix the include of extra_javascript

### PR DESCRIPTION
**Pull request by brunoruas2**
I was trying to use an additional js file according to the mkdocs documentation by passing the paths of the js files in the "extra_javascript" tag in mkdocs.yml, but it wasn't working.

When analyzing the code of the base.html file, I noticed that the import part of these files was missing. So I added it to the fork I made, and it worked for me.

image

### CODE REVIEW

**Review by FernandoCelmer — CHANGES_REQUESTED** [review]
Hello! Thanks for the contribution. 😃
Good review of that extra setting for javascript. There is just one detail, in your first commit [https://github.com/FernandoCelmer/mkdocs-simple-blog/pull/19/commits/e0286290ea410ee7237f8a10484c71cd9e33ee91](https://github.com/FernandoCelmer/mkdocs-simple-blog/pull/19/commits/e0286290ea410ee7237f8a10484c71cd9e33ee91) there was removal of files referring to the execution of the pipeline with extension '.yml' and the file 'setup.py', I need you to revert this commit or insert these files again , but preferably revert with the git revert command.

**Comment by brunoruas2** [comment]
I'm glad with your response! This first commit happened because when I forked your repository and cloned it using git, for some reason, only an empty repo with a .git file came.

I tried everything, but git pull origin master just kept saying everything was up to date even though my local repo was empty and the remote repo on GitHub was full of files.

So I downloaded the repo in .zip and copied it to my local repo. But when I run git add ., it showed me all these deleted files.

When I run the command git revert e028629, it gives me this error message: "error: invalid path 'template/assets/fonts/fontawesome-webfont.svg?v=4.7.0'".

**Comment by brunoruas2** [comment]
I will try to redo the process from scratch. I will keep you updated.

**Comment by brunoruas2** [comment]
I see! The issue is with the fontawesome-webfont.svg?v=4.7.0 file, because on Windows we cannot save files with the ? character.

**Comment by brunoruas2** [comment]
I'll do it correctly in the next PR.

**Pull request closed without merging**
